<?php

declare(strict_types=1);

namespace TeamSpeak\WebQuery\Responses\Servers;

use TeamSpeak\WebQuery\Enums\CodecEncryptionMode;
use TeamSpeak\WebQuery\Enums\HostBannerMode;
use TeamSpeak\WebQuery\Enums\HostMessageMode;

final readonly class InfoResponse
{
    private function __construct(
        public int $connectionBandwidthReceivedLastMinuteTotal,
        public int $connectionBandwidthReceivedLastSecondTotal,
        public int $connectionBandwidthSentLastMinuteTotal,
        public int $connectionBandwidthSentLastSecondTotal,
        public int $connectionBytesReceivedControl,
        public int $connectionBytesReceivedKeepalive,
        public int $connectionBytesReceivedSpeech,
        public int $connectionBytesReceivedTotal,
        public int $connectionBytesSentControl,
        public int $connectionBytesSentKeepalive,
        public int $connectionBytesSentSpeech,
        public int $connectionBytesSentTotal,
        public int $connectionFiletransferBandwidthReceived,
        public int $connectionFiletransferBandwidthSent,
        public int $connectionFiletransferBytesReceivedTotal,
        public int $connectionFiletransferBytesSentTotal,
        public int $connectionPacketsReceivedControl,
        public int $connectionPacketsReceivedKeepalive,
        public int $connectionPacketsReceivedSpeech,
        public int $connectionPacketsReceivedTotal,
        public int $connectionPacketsSentControl,
        public int $connectionPacketsSentKeepalive,
        public int $connectionPacketsSentSpeech,
        public int $connectionPacketsSentTotal,
        public int $antifloodPointsNeededCommandBlock,
        public int $antifloodPointsNeededIpBlock,
        public int $antifloodPointsNeededPluginBlock,
        public int $antifloodPointsTickReduce,
        public bool $askForPrivilegekey,
        public bool $autostart,
        public string $capabilityExtensions,
        public int $channelTempDeleteDelayDefault,
        public int $channelsOnline,
        public int $clientConnections,
        public int $clientsOnline,
        public CodecEncryptionMode $codecEncryptionMode,
        public int $complainAutobanCount,
        public int $complainAutobanTime,
        public int $complainRemoveTime,
        public int $created,
        public int $defaultChannelAdminGroup,
        public int $defaultChannelGroup,
        public int $defaultServerGroup,
        public int $downloadQuota,
        public string $fileStorageClass,
        public string $filebase,
        public bool $password,
        public int $hostbannerGfxInterval,
        public string $hostbannerGfxUrl,
        public HostBannerMode $hostbannerMode,
        public string $hostbannerUrl,
        public string $hostbuttonGfxUrl,
        public string $hostbuttonTooltip,
        public string $hostbuttonUrl,
        public string $hostmessage,
        public HostMessageMode $hostmessageMode,
        public int $iconId,
        public int $id,
        public string $ip,
        public bool $logChannel,
        public bool $logClient,
        public bool $logFileTransfer,
        public bool $logPermissions,
        public bool $logQuery,
        public bool $logServer,
        public string $machineId,
        public int $maxDownloadTotalBandwidth,
        public int $maxUploadTotalBandwidth,
        public int $maxClients,
        public int $minAndroidVersion,
        public int $minClientVersion,
        public int $minClientsInChannelBeforeForcedSilence,
        public int $minIosVersion,
        public int $monthBytesDownloaded,
        public int $monthBytesUploaded,
        public string $name,
        public string $namePhonetic,
        public int $neededIdentitySecurityLevel,
        public string $nickname,
        public string $passwordHash,
        public string $platform,
        public int $port,
        public float $prioritySpeakerDimmModificator,
        public int $queryClientConnections,
        public int $queryClientsOnline,
        public int $reservedSlots,
        public string $status,
        public int $totalBytesDownloaded,
        public int $totalBytesUploaded,
        public float $totalPacketlossControl,
        public float $totalPacketlossKeepalive,
        public float $totalPacketlossSpeech,
        public float $totalPacketlossTotal,
        public float $totalPing,
        public string $uniqueIdentifier,
        public int $uploadQuota,
        public int $uptime,
        public string $version,
        public bool $weblistEnabled,
        public string $welcomemessage,
    ) {}

    /**
     * @param  array{0: array{connection_bandwidth_received_last_minute_total: string, connection_bandwidth_received_last_second_total: string, connection_bandwidth_sent_last_minute_total: string, connection_bandwidth_sent_last_second_total: string, connection_bytes_received_control: string, connection_bytes_received_keepalive: string, connection_bytes_received_speech: string, connection_bytes_received_total: string, connection_bytes_sent_control: string, connection_bytes_sent_keepalive: string, connection_bytes_sent_speech: string, connection_bytes_sent_total: string, connection_filetransfer_bandwidth_received: string, connection_filetransfer_bandwidth_sent: string, connection_filetransfer_bytes_received_total: string, connection_filetransfer_bytes_sent_total: string, connection_packets_received_control: string, connection_packets_received_keepalive: string, connection_packets_received_speech: string, connection_packets_received_total: string, connection_packets_sent_control: string, connection_packets_sent_keepalive: string, connection_packets_sent_speech: string, connection_packets_sent_total: string, virtualserver_antiflood_points_needed_command_block: string, virtualserver_antiflood_points_needed_ip_block: string, virtualserver_antiflood_points_needed_plugin_block: string, virtualserver_antiflood_points_tick_reduce: string, virtualserver_ask_for_privilegekey: string, virtualserver_autostart: string, virtualserver_capability_extensions: string, virtualserver_channel_temp_delete_delay_default: string, virtualserver_channelsonline: string, virtualserver_client_connections: string, virtualserver_clientsonline: string, virtualserver_codec_encryption_mode: string, virtualserver_complain_autoban_count: string, virtualserver_complain_autoban_time: string, virtualserver_complain_remove_time: string, virtualserver_created: string, virtualserver_default_channel_admin_group: string, virtualserver_default_channel_group: string, virtualserver_default_server_group: string, virtualserver_download_quota: string, virtualserver_file_storage_class: string, virtualserver_filebase: string, virtualserver_flag_password: string, virtualserver_hostbanner_gfx_interval: string, virtualserver_hostbanner_gfx_url: string, virtualserver_hostbanner_mode: string, virtualserver_hostbanner_url: string, virtualserver_hostbutton_gfx_url: string, virtualserver_hostbutton_tooltip: string, virtualserver_hostbutton_url: string, virtualserver_hostmessage: string, virtualserver_hostmessage_mode: string, virtualserver_icon_id: string, virtualserver_id: string, virtualserver_ip: string, virtualserver_log_channel: string, virtualserver_log_client: string, virtualserver_log_filetransfer: string, virtualserver_log_permissions: string, virtualserver_log_query: string, virtualserver_log_server: string, virtualserver_machine_id: string, virtualserver_max_download_total_bandwidth: string, virtualserver_max_upload_total_bandwidth: string, virtualserver_maxclients: string, virtualserver_min_android_version: string, virtualserver_min_client_version: string, virtualserver_min_clients_in_channel_before_forced_silence: string, virtualserver_min_ios_version: string, virtualserver_month_bytes_downloaded: string, virtualserver_month_bytes_uploaded: string, virtualserver_name: string, virtualserver_name_phonetic: string, virtualserver_needed_identity_security_level: string, virtualserver_nickname: string, virtualserver_password: string, virtualserver_platform: string, virtualserver_port: string, virtualserver_priority_speaker_dimm_modificator: string, virtualserver_query_client_connections: string, virtualserver_queryclientsonline: string, virtualserver_reserved_slots: string, virtualserver_status: string, virtualserver_total_bytes_downloaded: string, virtualserver_total_bytes_uploaded: string, virtualserver_total_packetloss_control: string, virtualserver_total_packetloss_keepalive: string, virtualserver_total_packetloss_speech: string, virtualserver_total_packetloss_total: string, virtualserver_total_ping: string, virtualserver_unique_identifier: string, virtualserver_upload_quota: string, virtualserver_uptime: string, virtualserver_version: string, virtualserver_weblist_enabled: string, virtualserver_welcomemessage: string}}  $attributes
     */
    public static function from(array $attributes): self
    {
        return new self(
            (int) $attributes[0]['connection_bandwidth_received_last_minute_total'],
            (int) $attributes[0]['connection_bandwidth_received_last_second_total'],
            (int) $attributes[0]['connection_bandwidth_sent_last_minute_total'],
            (int) $attributes[0]['connection_bandwidth_sent_last_second_total'],
            (int) $attributes[0]['connection_bytes_received_control'],
            (int) $attributes[0]['connection_bytes_received_keepalive'],
            (int) $attributes[0]['connection_bytes_received_speech'],
            (int) $attributes[0]['connection_bytes_received_total'],
            (int) $attributes[0]['connection_bytes_sent_control'],
            (int) $attributes[0]['connection_bytes_sent_keepalive'],
            (int) $attributes[0]['connection_bytes_sent_speech'],
            (int) $attributes[0]['connection_bytes_sent_total'],
            (int) $attributes[0]['connection_filetransfer_bandwidth_received'],
            (int) $attributes[0]['connection_filetransfer_bandwidth_sent'],
            (int) $attributes[0]['connection_filetransfer_bytes_received_total'],
            (int) $attributes[0]['connection_filetransfer_bytes_sent_total'],
            (int) $attributes[0]['connection_packets_received_control'],
            (int) $attributes[0]['connection_packets_received_keepalive'],
            (int) $attributes[0]['connection_packets_received_speech'],
            (int) $attributes[0]['connection_packets_received_total'],
            (int) $attributes[0]['connection_packets_sent_control'],
            (int) $attributes[0]['connection_packets_sent_keepalive'],
            (int) $attributes[0]['connection_packets_sent_speech'],
            (int) $attributes[0]['connection_packets_sent_total'],
            (int) $attributes[0]['virtualserver_antiflood_points_needed_command_block'],
            (int) $attributes[0]['virtualserver_antiflood_points_needed_ip_block'],
            (int) $attributes[0]['virtualserver_antiflood_points_needed_plugin_block'],
            (int) $attributes[0]['virtualserver_antiflood_points_tick_reduce'],
            (bool) $attributes[0]['virtualserver_ask_for_privilegekey'],
            (bool) $attributes[0]['virtualserver_autostart'],
            $attributes[0]['virtualserver_capability_extensions'],
            (int) $attributes[0]['virtualserver_channel_temp_delete_delay_default'],
            (int) $attributes[0]['virtualserver_channelsonline'],
            (int) $attributes[0]['virtualserver_client_connections'],
            (int) $attributes[0]['virtualserver_clientsonline'],
            CodecEncryptionMode::from((int) $attributes[0]['virtualserver_codec_encryption_mode']),
            (int) $attributes[0]['virtualserver_complain_autoban_count'],
            (int) $attributes[0]['virtualserver_complain_autoban_time'],
            (int) $attributes[0]['virtualserver_complain_remove_time'],
            (int) $attributes[0]['virtualserver_created'],
            (int) $attributes[0]['virtualserver_default_channel_admin_group'],
            (int) $attributes[0]['virtualserver_default_channel_group'],
            (int) $attributes[0]['virtualserver_default_server_group'],
            (int) $attributes[0]['virtualserver_download_quota'],
            $attributes[0]['virtualserver_file_storage_class'],
            $attributes[0]['virtualserver_filebase'],
            (bool) $attributes[0]['virtualserver_flag_password'],
            (int) $attributes[0]['virtualserver_hostbanner_gfx_interval'],
            $attributes[0]['virtualserver_hostbanner_gfx_url'],
            HostBannerMode::from((int) $attributes[0]['virtualserver_hostbanner_mode']),
            $attributes[0]['virtualserver_hostbanner_url'],
            $attributes[0]['virtualserver_hostbutton_gfx_url'],
            $attributes[0]['virtualserver_hostbutton_tooltip'],
            $attributes[0]['virtualserver_hostbutton_url'],
            $attributes[0]['virtualserver_hostmessage'],
            HostMessageMode::from((int) $attributes[0]['virtualserver_hostmessage_mode']),
            (int) $attributes[0]['virtualserver_icon_id'],
            (int) $attributes[0]['virtualserver_id'],
            $attributes[0]['virtualserver_ip'],
            (bool) $attributes[0]['virtualserver_log_channel'],
            (bool) $attributes[0]['virtualserver_log_client'],
            (bool) $attributes[0]['virtualserver_log_filetransfer'],
            (bool) $attributes[0]['virtualserver_log_permissions'],
            (bool) $attributes[0]['virtualserver_log_query'],
            (bool) $attributes[0]['virtualserver_log_server'],
            $attributes[0]['virtualserver_machine_id'],
            (int) $attributes[0]['virtualserver_max_download_total_bandwidth'],
            (int) $attributes[0]['virtualserver_max_upload_total_bandwidth'],
            (int) $attributes[0]['virtualserver_maxclients'],
            (int) $attributes[0]['virtualserver_min_android_version'],
            (int) $attributes[0]['virtualserver_min_client_version'],
            (int) $attributes[0]['virtualserver_min_clients_in_channel_before_forced_silence'],
            (int) $attributes[0]['virtualserver_min_ios_version'],
            (int) $attributes[0]['virtualserver_month_bytes_downloaded'],
            (int) $attributes[0]['virtualserver_month_bytes_uploaded'],
            $attributes[0]['virtualserver_name'],
            $attributes[0]['virtualserver_name_phonetic'],
            (int) $attributes[0]['virtualserver_needed_identity_security_level'],
            $attributes[0]['virtualserver_nickname'],
            $attributes[0]['virtualserver_password'],
            $attributes[0]['virtualserver_platform'],
            (int) $attributes[0]['virtualserver_port'],
            (float) $attributes[0]['virtualserver_priority_speaker_dimm_modificator'],
            (int) $attributes[0]['virtualserver_query_client_connections'],
            (int) $attributes[0]['virtualserver_queryclientsonline'],
            (int) $attributes[0]['virtualserver_reserved_slots'],
            $attributes[0]['virtualserver_status'],
            (int) $attributes[0]['virtualserver_total_bytes_downloaded'],
            (int) $attributes[0]['virtualserver_total_bytes_uploaded'],
            (float) $attributes[0]['virtualserver_total_packetloss_control'],
            (float) $attributes[0]['virtualserver_total_packetloss_keepalive'],
            (float) $attributes[0]['virtualserver_total_packetloss_speech'],
            (float) $attributes[0]['virtualserver_total_packetloss_total'],
            (float) $attributes[0]['virtualserver_total_ping'],
            $attributes[0]['virtualserver_unique_identifier'],
            (int) $attributes[0]['virtualserver_upload_quota'],
            (int) $attributes[0]['virtualserver_uptime'],
            $attributes[0]['virtualserver_version'],
            (bool) $attributes[0]['virtualserver_weblist_enabled'],
            $attributes[0]['virtualserver_welcomemessage'],
        );
    }
}
