<?php

declare(strict_types=1);

namespace TeamSpeak\WebQuery\Responses\Clients;

use DateTimeImmutable;
use TeamSpeak\WebQuery\Enums\ClientType;

final readonly class InfoResponse
{
    /**
     * @param  list<int>  $serverGroups
     */
    private function __construct(
        public int $id,
        public bool $away,
        public string $awayMessage,
        public string $badges,
        public string $base64HashClientUID,
        public int $channelGroupId,
        public int $channelGroupInheritedChannelId,
        public string $country,
        public DateTimeImmutable $created,
        public int $databaseId,
        public string $defaultChannel,
        public string $defaultToken,
        public string $description,
        public string $flagAvatar,
        public int $iconId,
        public int $idleTime,
        public bool $inputHardware,
        public bool $inputMuted,
        public int $integrations,
        public bool $channelCommander,
        public bool $prioritySpeaker,
        public bool $recording,
        public bool $talker,
        public DateTimeImmutable $lastConnected,
        public string $loginName,
        public string $metaData,
        public int $monthBytesDownloaded,
        public int $monthBytesUploaded,
        public string $myTeamSpeakAvatar,
        public string $myTeamSpeakId,
        public int $neededServerQueryViewPower,
        public string $nickname,
        public string $nicknamePhonetic,
        public bool $outputHardware,
        public bool $outputMuted,
        public bool $outputOnlyMuted,
        public string $platform,
        public string $securityHash,
        public array $serverGroups,
        public string $signedBadges,
        public int $talkPower,
        public bool $talkRequest,
        public string $talkRequestMessage,
        public int $totalBytesDownloaded,
        public int $totalBytesUploaded,
        public int $totalConnections,
        public ClientType $type,
        public string $uniqueIdentifier,
        public string $version,
        public string $versionSign,
        public int $bandwidthReceivedLastMinuteTotal,
        public int $bandwidthReceivedLastSecondTotal,
        public int $bandwidthSentLastMinuteTotal,
        public int $bandwidthSentLastSecondTotal,
        public int $bytesReceivedTotal,
        public int $bytesSentTotal,
        public string $ipAddress,
        public int $connectedTime,
        public int $fileTransferBandwidthReceived,
        public int $fileTransferBandwidthSent,
        public int $packetsReceivedTotal,
        public int $packetsSentTotal,
    ) {}

    /**
     * @param  array{0: array{cid: string, client_away: string, client_away_message: string, client_badges: string, client_base64HashClientUID: string, client_channel_group_id: string, client_channel_group_inherited_channel_id: string, client_country: string, client_created: string, client_database_id: string, client_default_channel: string, client_default_token: string, client_description: string, client_flag_avatar: string, client_icon_id: string, client_idle_time: string, client_input_hardware: string, client_input_muted: string, client_integrations: string, client_is_channel_commander: string, client_is_priority_speaker: string, client_is_recording: string, client_is_talker: string, client_lastconnected: string, client_login_name: string, client_meta_data: string, client_month_bytes_downloaded: string, client_month_bytes_uploaded: string, client_myteamspeak_avatar: string, client_myteamspeak_id: string, client_needed_serverquery_view_power: string, client_nickname: string, client_nickname_phonetic: string, client_output_hardware: string, client_output_muted: string, client_outputonly_muted: string, client_platform: string, client_security_hash: string, client_servergroups: string, client_signed_badges: string, client_talk_power: string, client_talk_request: string, client_talk_request_msg: string, client_total_bytes_downloaded: string, client_total_bytes_uploaded: string, client_totalconnections: string, client_type: string, client_unique_identifier: string, client_version: string, client_version_sign: string, connection_bandwidth_received_last_minute_total: string, connection_bandwidth_received_last_second_total: string, connection_bandwidth_sent_last_minute_total: string, connection_bandwidth_sent_last_second_total: string, connection_bytes_received_total: string, connection_bytes_sent_total: string, connection_client_ip: string, connection_connected_time: string, connection_filetransfer_bandwidth_received: string, connection_filetransfer_bandwidth_sent: string, connection_packets_received_total: string, connection_packets_sent_total: string}}  $attributes
     */
    public static function from(array $attributes): self
    {
        return new self(
            (int) $attributes[0]['cid'],
            (bool) $attributes[0]['client_away'],
            $attributes[0]['client_away_message'],
            $attributes[0]['client_badges'],
            $attributes[0]['client_base64HashClientUID'],
            (int) $attributes[0]['client_channel_group_id'],
            (int) $attributes[0]['client_channel_group_inherited_channel_id'],
            $attributes[0]['client_country'],
            DateTimeImmutable::createFromTimestamp((int) $attributes[0]['client_created']),
            (int) $attributes[0]['client_database_id'],
            $attributes[0]['client_default_channel'],
            $attributes[0]['client_default_token'],
            $attributes[0]['client_description'],
            $attributes[0]['client_flag_avatar'],
            (int) $attributes[0]['client_icon_id'],
            (int) $attributes[0]['client_idle_time'],
            (bool) $attributes[0]['client_input_hardware'],
            (bool) $attributes[0]['client_input_muted'],
            (int) $attributes[0]['client_integrations'],
            (bool) $attributes[0]['client_is_channel_commander'],
            (bool) $attributes[0]['client_is_priority_speaker'],
            (bool) $attributes[0]['client_is_recording'],
            (bool) $attributes[0]['client_is_talker'],
            DateTimeImmutable::createFromTimestamp((int) $attributes[0]['client_lastconnected']),
            $attributes[0]['client_login_name'],
            $attributes[0]['client_meta_data'],
            (int) $attributes[0]['client_month_bytes_downloaded'],
            (int) $attributes[0]['client_month_bytes_uploaded'],
            $attributes[0]['client_myteamspeak_avatar'],
            $attributes[0]['client_myteamspeak_id'],
            (int) $attributes[0]['client_needed_serverquery_view_power'],
            $attributes[0]['client_nickname'],
            $attributes[0]['client_nickname_phonetic'],
            (bool) $attributes[0]['client_output_hardware'],
            (bool) $attributes[0]['client_output_muted'],
            (bool) $attributes[0]['client_outputonly_muted'],
            $attributes[0]['client_platform'],
            $attributes[0]['client_security_hash'],
            array_map(fn (string $value): int => (int) $value, explode(',', $attributes[0]['client_servergroups'])),
            $attributes[0]['client_signed_badges'],
            (int) $attributes[0]['client_talk_power'],
            (bool) $attributes[0]['client_talk_request'],
            $attributes[0]['client_talk_request_msg'],
            (int) $attributes[0]['client_total_bytes_downloaded'],
            (int) $attributes[0]['client_total_bytes_uploaded'],
            (int) $attributes[0]['client_totalconnections'],
            ClientType::from((int) $attributes[0]['client_type']),
            $attributes[0]['client_unique_identifier'],
            $attributes[0]['client_version'],
            $attributes[0]['client_version_sign'],
            (int) $attributes[0]['connection_bandwidth_received_last_minute_total'],
            (int) $attributes[0]['connection_bandwidth_received_last_second_total'],
            (int) $attributes[0]['connection_bandwidth_sent_last_minute_total'],
            (int) $attributes[0]['connection_bandwidth_sent_last_second_total'],
            (int) $attributes[0]['connection_bytes_received_total'],
            (int) $attributes[0]['connection_bytes_sent_total'],
            $attributes[0]['connection_client_ip'],
            (int) $attributes[0]['connection_connected_time'],
            (int) $attributes[0]['connection_filetransfer_bandwidth_received'],
            (int) $attributes[0]['connection_filetransfer_bandwidth_sent'],
            (int) $attributes[0]['connection_packets_received_total'],
            (int) $attributes[0]['connection_packets_sent_total'],
        );
    }
}
